apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80         # The port that the service will be exposed on
    targetPort: 5000 # The port your Flask app is listening on
  type: LoadBalancer

